### ISSUE TITLE
Confirm Cassandra Compactor Works

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#1062]
For scrub [and potentially sweep], we want to make sure the Cassandra JMX compactor is functioning as we'd expect it so we can actually reclaim space / remove data from disk after we've deleted it from Cassandra.

I think everything here should be fine as it is, but likely could benefit from some ETE tests.

@clockfort @ashrayjain

**Comment by clockfort** [comment]
Things that are lame related to this:
- No one uses this in the field
- We don't test it, and it would need some massaging of the docker Cassandra container that we ship for tests in Circle in order to get this to work
- SLS Cassandra needs extra logic around it; very similar to our required 2-way SSL magic, there needs to be a way to set up generated JMX credentials automatically and somehow place them on both Cassandra and Atlas configuration side

**Comment by jboreiko** [comment]
This will not be prioritized soon.  We would push for people to use manual / scheduled compactions to achieve this end.  We would be willing to accept changes.
