### ISSUE TITLE
Leader block docs ER

### ISSUE THREAD

**Issue by sarahfbeller** [palantir/atlasdb#1163]
// From PDS-46456

Potential docs feedback: The leader block is agnostic to specific backend and only cares about the server hosting the Atlas client. I'd change localhost -> FQDN of the actual AtlasDB client application server in question and port to the application API port (where Atlas registers the relevant endpoints). Ultimately think the hostname needs to be whatever makes your SSL cert validation happy. This stuff is typically automatically wired up in service discovery.

**Comment by rhero** [comment]
Just read the support ticket, and I actually don't think any changes should be made to this page: http://palantir.github.io/atlasdb/html/configuration/leader_config.html.

The "cluster" and "nodes" that are being referenced in this page are actually in reference to the cluster of AtlasDB clients. I can maybe add a note that says "when we say cluster, we mean cluster of atlasdb clients", but I don't think there are any changes to the actual examples. I much prefer to err on the side of being explicit in the Cassandra case vs being agnostic to the postgres case since most customers use Cassandra.

I'll make a note that cluster and node are in reference to AtlasDB clients, and then probably close this out.
