### ISSUE TITLE
Transaction layer index

### ISSUE THREAD

**Issue by EthanLozano** [palantir/atlasdb#1202]
AtlasDB currently only supports indices at the [code generation layer](http://palantir.github.io/atlasdb/html/schemas/tables_and_indices.html), which means that the indexes can easily get out of sync with the main table. If possible, could AtlasDB automatically create indexes at the KVS/Transaction layer so that the user isn't responsible for managing index tables?

**Comment by tpetracca** [comment]
@EthanLozano I might not know the index code generation stuff very well but it's unclear that the user is responsible for managing index tables? All you have to do is define an index and it just works doesn't it?

**Comment by rhero** [comment]
Hey @EthanLozano - can you give an explicit example of what guarantees you're expecting when using AtlasDB indexes and what behavior you actually see? I'm not sure I follow what you're expecting.

**Comment by jboreiko** [comment]
Now realizing this is related to an internal email thread, quotes here:

Original question (truncated slightly)
"we have the need for an inverted index (find the key associated with a value). Currently, we have really inefficient reverse lookup procedures that traverse the entire table to find the inverse mapping. We are considering creating and populating an inverted index ourselves (value -> key). But, managing an inverted index means that we are bloating our codebase with code that is usually managed by a database. Also, a developer has to remember to update the index every place they modify the mapping table, which means that future developers will likely screw this up. Also, we have to manually write upgrade tasks to initially build the index tables, which could also have bugs. So, does AtlasDB have plans to build the feature of automatically building an inverted index?"

@gbonik 's response
"Atlas actually supports automatic index generation via Schema.addIndexDefinition(). For example, <redacted>. However, this feature has a lot of drawbacks and arguably shouldn't even exist in its current form:
If you use an ADDITIVE index, your data will never be cleaned up from the index, so you'll have to do manual postfiltering using the main table which could be a huge perf hit and still requires code.
 If you use a CELL_REFERENCING index, you get extra overhead for storing the cell keys from the original table in each index entry
Both are a pain if you ever need to write an upgrade task to change the format of the index or the main table
These indexes only "exist" in the generated code layer anyway, not the KVS/Transaction layer. For example, a write to a table performed using Atlas Shell will not update the indexes because it simply doesn't know anything about the indexes.
If I was designing a new Atlas schema, I'd probably bite the bullet and write the code to manage the index myself. This gives you more control, and very often you can implement it yourself much more efficiently than atlas does it automatically. Some folks would probably disagree here"

**Comment by EthanLozano** [comment]
My project decided against using the code generated indexes due to the drawbacks listed by @gbonik; specifically, performance is important for my project, so it was more efficient to manage the indexes ourselves. However, we now have the drawbacks that are listed by @jboreiko.

AtlasDB might not be designed to fulfill what I'm requesting, but here are the guarantees that I would like:
- The index is no more storage intensive than if I managed the index myself
- Updating the index is as efficient as if I managed the index myself
- I do not need to write an upgrade task to change the index if the main table changes
- I do not need to write an upgrade task to create a new index (or when I change an existing index)
- [not too important] If a user changes the main table in Atlas Shell, then the index tables are automatically updated

**Comment by EthanLozano** [comment]
It would be nice if you could define an AtlasDB index similar to how indexes are created in existing databases:

- [postgres create index](https://www.postgresql.org/docs/9.6/static/sql-createindex.html)
- [casandra create index](https://docs.datastax.com/en/cql/3.3/cql/cql_reference/create_index_r.html)

I understand that transaction protocol probably wouldn't make this possible, but it would be ideal if the indexes were managed by the underlying database's index implementation to guarantee optimal performance

**Comment by jboreiko** [comment]
Might be best to sync about the particular use case and where you guys are currently at.  If we were to adopt this work, it would be essential that we would closely with you guys to deliver something that would be valuable to you as well as others.
