### ISSUE TITLE
Shorten table names across all KVSs

### ISSUE THREAD

**Issue by pwilczynski** [palantir/atlasdb#1350]
Per Ryan Zheng, Postgres imposes a 63 character table name size limit.

My recommendation would be to refactor the [OracleTableNameMapper](https://github.com/palantir/atlasdb/blob/faf71a7a15d78ddda8a01b8fe965fdb4ca79b2d7/atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameMapper.java#L27) to support Postgres as well.

**Comment by clockfort** [comment]
Ideally this would be done in a way that maps the table names to the exact same ones that postgres already has, else the upgrade will be a nightmare

**Comment by sfackler** [comment]
We just hit this with distinct table names that share a 63 character prefix. 🔥 

I guess we're stuck on the jdbc driver until this is implemented?

**Comment by jboreiko** [comment]
@carrino / @sfackler / @rhero all synced on this.  We concluded that we will pursue the following steps:
- [ ] hard fail on DBKVS postgres names exceeding 63 characters to ensure we don't have silent failures
- [ ] accept a table remapping PR if it's pursued by the RR team.  This will need to take into account @clockfort 's comment above as we do not want to cause manual steps for existing customers (might also be reasonable to have it be optional to get around this).

**Comment by gsheasby** [comment]
@hsaraogi will try to get to adding the hard failure in the near future

**Comment by rhero** [comment]
Hi all,

Was going through old tickets and I forgot that the postgres name mapping PR didn't actually merge. We didn't look into the hard fail solution because that was in progress, and we never revisited this.

@jboreiko, @hsaraogi  or @clockfort - do you guys see any immediate issues with throwing an exception when trying to create table names longer than 63 characters? Mostly interested if this is a small, low risk thing we can just do quickly. It seems like there might be an issue if you had a table name with 64+ characters installed on Oracle, and then KVS migrate to Postgres, but that scenario might be sufficiently rare that we don't need to address it for awhile.

**Comment by gsheasby** [comment]
The suggested solution has been merged - are we now OK to close this? Is there a separate ticket to track a "Postgres Table Mapping Service" or are we no longer planning to get to this?

@hsaraogi @clockfort

**Comment by clockfort** [comment]
A more universal mapper would still be nice; there's a team that has already deployed 63+ character names and have already experienced the pain of overlapping tablenames on postgres in prod, and another dev team who made some new indexes (with a longer name) was hyper-confused until I told them they were also running into this same bug.

**Comment by clockfort** [comment]
Throwing would be okay, except we have some essentially user-controlled table names, so the error would have to at least be fairly good, and we already have at least one deployment past the limit already.

(the user-controlled table names usually have the name referring to some dataset)

**Comment by rhero** [comment]
The core problem for this issue was we were accidentally creating two tables with the same name for Postgres, and would silently corrupt data. So I think we sufficiently avoid that now. The [error message](https://github.com/palantir/atlasdb/pull/1729/files#diff-796dee97c01c303badcbcccc216de1f5R81) seems pretty informative, but I guess we'll find out when the first person hits the issue and asks for help.

The ticket created for the universal table mapper/allowing arbitrarily long table names for all KVSs seems to be captured by #1518, so I'm going to close this one out.
