### ISSUE TITLE
Create Jepsen nemesis for service failure

### ISSUE THREAD

**Issue by rhero** [palantir/atlasdb#1431]
We currently only have one nemesis, which performs network partitions between services. We should add another nemesis to simulate service failures. I'm not sure if it's worth distinguishing between host failure, service failure, and service OOMs, but we should have at least one test for this scenario as this is far more common than actual network partitions.

**Comment by gsheasby** [comment]
Related to #1407.

**Comment by gsheasby** [comment]
@harrybiddle for SA

**Comment by jeremyk-91** [comment]
An idea @jboreiko mentioned (maybe part of this ticket, or if not it should be spun off somewhere): we should see what happens if we blow away the acceptor / learner log directories of a minority / all but one node - can we still recover in these cases? (We should *definitely* recover from the minority; the all but 1 case is more interesting and might actually work from my skimming of the code - while I'm skeptical it could be worth a shot.)

**Comment by rhero** [comment]
Pretty sure this is done, including the part @jeremyk-91 mentioned. I can't find the PR where we add it. @harrybiddle @gmaretic can you guys link it here and then close this?

**Comment by gsheasby** [comment]
Probably related to a combination of there: https://github.com/palantir/atlasdb/pulls?q=is%3Apr+label%3A%22component%3A+HA%22+is%3Aclosed

Closing - @gmaretic, shout if we're wrong to close this!

**Comment by harrybiddle** [comment]
This is hanging around on a branch, but isn't in yet :(. Currently the only nemeses running are [partition-random-halves](https://github.com/palantir/atlasdb/blob/develop/atlasdb-jepsen-tests/src/jepsen/atlasdb/timestamp.clj#L65), and even then the CI job is currently broken/flakey.

Specifically, the nemeses are on the branch "jepsen/paxos". It's called ['crash-nemesis'](https://github.com/palantir/atlasdb/blob/jepsen/paxos/atlasdb-jepsen-tests/src/jepsen/atlasdb/timelock.clj#L70), and does a stop/rm -f/start. It'll just require a bit of plumbing to merge it in to develop; @gmaretic I'd be happy to pair on this if you would like. Ideally next week for me.

Re-opening on the assuming that you'd closed this because you thought it was done rather than because you've deprioritised it.

**Comment by gmaretic** [comment]
Let's do this next week

**Comment by gmaretic** [comment]
Merged
