### ISSUE TITLE
Give SnapTrans#getRanges a better API

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#1520]
Request came in from agreene for a better / more responsive getRanges API.

Current method signature is:
```
public Iterable<BatchingVisitable<RowResult<byte[]>>> getRanges(final TableReference tableRef,
                                                                    Iterable<RangeRequest> rangeRequests) {
```
The impl is unfortunate, because it blocks until you get back the first page from each of the ranges before you can return anything to the user.

@jboreiko and I were thinking maybe a nicer API would be to return a `Map<RangeRequest, Stream>`, or possibly have this and another utility method that takes that and performs the parallelism for the user to make it easier on them, and give back a single unordered parallel stream. (which sometimes would not be the ideal API for some people, especially people who could otherwise have stopped reading a certain longer range after they got enough of the data out of it they wanted)

**Comment by rhero** [comment]
What's the priority/value of improving this? It's not clear how an internal product is hoping to take advantage of this or if it's urgent.

**Comment by agreenepal** [comment]
Hey - I think there are a few independent concerns - 

(1) Ideally, we would not need to load all of the column data to load rownames when invoking atlas external APIs. You cannot specify an empty column selection, yet internally atlas performs this mapping when accepting a RangeRequest.

(2) An impetus for (1) is that some interfaces to atlas accept Iterable<Row> - while sometimes I am able to build these collections in memory, there are other times where I'd like to specify a RangeRequest, but am unable. Since I have no interface via which to map RangeRequest -> Iterable<byte[]> or Iterable<Row> I am left unable to actually specify this parameter. One example would be when using getRowsColumnRange - I cannot specify a RangeRequest to this interface, and I cannot map a RangeRequest to the required rownames.

(3) The implementation of getRanges is a little inefficient in that by calling getRanges my code blocks. I'd prefer to only block after I've decided to request results from whatever reference you've returned to me.

An example pressing concern is that getRowsColumnRange accepts an Iterable of rownames (makes sense) but I have no means to actually produce an Iterable of rownames from a RangeRequest (so, I can describe a partition of rownames, but I can never actually get them without also loading all column data)

**Comment by jboreiko** [comment]
Discussed a bit with @clockfort 

To start thinking about 1) we can certainly offer an endpoint that returns only rows (accumulation of row components) and no columns or value data.  In order to have this actually represent savings we would have to construct cql queries to request only the row from cassandra something along the lines of `select row, column2 from <table> where row >= <lower-bound> and row < <upper-bound>`.  

The hope here is that this just hits the primary key index(es) in cassandra and doesn't actually read the sstables to service the query.  My concern now becomes we need to be able to retrieve the timestamps associated with each row entry to ensure the row is actually visible to the transactions, this is column2.  This would still require a full scan of all the row + (column components associated with the row) to service, which could be quite heavy but may be worth the gain since we should be able to avoid the sstable reads.

**Comment by sandorw** [comment]
Not currently planning to iterate on core APIs given lack of recent need for changes.
