### ISSUE TITLE
Docs for running the Console to access data directly

### ISSUE THREAD

**Issue by fryz** [palantir/atlasdb#1585]

**Comment by rhero** [comment]
Hey @fryz - what kind of documentation were you looking for exactly? I notice that on the console page we don't have an example of how to start the console, so we should probably have those. Anything more detailed we're probably not going to prioritize because there are some internal docs for a specific product that are pretty good, and I don't think generalizing them would be particularly valuable.

Thoughts?

**Comment by fryz** [comment]
I'd be cool with just how to start it - would be even better if we could get some bare-minimum how to use it (starting transactions, getting rows, committing transactions, etc.)
