### ISSUE TITLE
Make sure Atlas Shell and Atlas Console are being built correctly / usable

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#160]
Lee reports https://jcenter.bintray.com/com/palantir/atlasdb/atlasdb-shell/0.3.23/  isn't built correctly and gives JNI errors.

Tim isn't sure if we even ship the frontend portion of atlas console to OSS atlas.

Ticket made for tracking investigation / fixing.

**Comment by markelliot** [comment]
Jcenter won't resolve unless you also have bintray in the repo list because of the publishing setup.

Sent from my iPhone

On Jan 8, 2016, at 4:53 PM, Chris Lockfort <notifications@github.com<mailto:notifications@github.com>> wrote:


Lee reports https://jcenter.bintray.com/com/palantir/atlasdb/atlasdb-shell/0.3.23/<https://urldefense.proofpoint.com/v2/url?u=https-3A__jcenter.bintray.com_com_palantir_atlasdb_atlasdb-2Dshell_0.3.23_&d=CwMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=uma3pU5ydP8Rmjlxd0CCAI-n2udVUfW2WyHnljanMTg&s=bbAFyXvmjn8qfhOBOwz4xFhobx_FcXwcH60mu0h0PEg&e=> isn't built correctly and gives JNI errors.

Tim isn't sure if we even ship the frontend portion of atlas console to OSS atlas.

Ticket made for tracking investigation / fixing.

**Comment by jboreiko** [comment]
Closing out as atlasdb-shell no longer exists in the OSS repo.
