### ISSUE TITLE
Check that the service has fast-forwarded before it can getFreshTimestamp

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1741]
This is necessary for taking meaningful backups. If the service has a timelock block in the config and has not migrated yet, we get the backup timestamp from timelock server which will be 1 (perhaps 0) and if we happen to restore this backup all data will be lost.

**Comment by tpetracca** [comment]
Generally speaking I don't think we should be creating namespaces until a client has explicitly requested to create it (and that create request can optionally allow you to specify a start timestamp).

I'm not a huge fan of the whole TimeLock generates namespaces via config thing.

**Comment by rhero** [comment]
Yeah, initializing the namespace via config probably isn't the best solution, but I don't think this should block the internal rollout of backups or the Timelock server. Reason being that that edge case for an incorrect backup is sufficiently unlikely and recovery is technically possible (albeit manual) given nobody should be manually adding the `timelock` config block.

To elaborate, these conditions must happen to take a bad backup:
- Start with a running AtlasDB client using an embedded timestamp service
- Install the Timelock server
- Modify the AtlasDB client config to contain a timelock block. The AtlasDB client is still using the embedded service though because it hasn't restarted.
- Modify the Timelock config to expose the client namespace, start Timelock
- Take a backup using timelock (grab the 0 or 1 timestamp)
- Use that backup to recover from some scenario, discover that cleaning the transaction table wipes all of your data after timestamp 0

I think this scenario isn't worth addressing with additional complexity because:
- We will be shipping default `timelock` config blocks in our products, so clients pick this up after upgrading, and thus will not be running when the config is added
- If you start Timelock at this point, you can expose the new client namespace and take a bad backup, but our backup product also takes a backup of the KVS, which should have a good timestamp stored in the _timestamp table (because the service is off).

**Comment by tpetracca** [comment]
@hsaraogi will TimeLock live reload config and create namespaces on the fly, or does it only happen on start-up? If the latter @rhero, then the other thing to consider is that migrating any AtlasDB client then means TimeLock must be bounced which hurts availability of ALL atlasdb clients using that timelock.

**Comment by tpetracca** [comment]
To be clear, I'm on-board with the whole backup thing not being a blocker to roll out.

**Comment by rhero** [comment]
Forgot to come back and comment here - I don't think we're going to add a check ensuring we've fast-forwarded before issuing timestamps, but I think it's worth a serious look at initializing namespaces via something other than config, so closing this out in favor of #1776.
