### ISSUE TITLE
Live Reload TimeLock Clients Block

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#1771]
When migrating services to TimeLock, we need to bounce the TimeLock cluster. Rolling restart while in practice feasible does carry a minuscule risk of corruption. Live reloading the clients block would be useful.

As a warning: live reloading the _cluster_ config is complex. For Paxos, in practice this often manifests as having K Paxos rounds for which you need majorities in both the old and new cluster configurations, after which you can decommission the old cluster.

**Comment by tpetracca** [comment]
I think the direction we want to move here is not to make the client block live-reloadable so much as to remove it entirely. I think we're better off just having the ability to create a namespace as a client. At migration time you can just say "create my namespace X with a start timestamp of Y".

Few reasons why I like this:
- Consumers that attempt to read at a namespace that hasn't been migrated to yet will receive whatever the "this namespace doesn't exist" error is instead of an incorrect value
- It allows for arbitrary consumers of timelock without modifying config
- No need to reason about how live-reloading works with Paxos
- No reason to bounce timelock for a new client

**Comment by rhero** [comment]
Moving this into To Do because the pain of rolling out Timelock internally will be very painful if clients aren't live reloaded (and you need to bounce Timelock after upgrading clients that may require Timelock).

The config based namespace seems like the simplest and quickest way to avoid this pain, but I do see the value in allowing clients to register their own namespaces without modifying config. Opening up a separate issue to track that #1776.

**Comment by hsaraogi** [comment]
Not prioritising as we want to discuss the option of using endpoints for registering clients versus using the config.

**Comment by gsheasby** [comment]
@nziebart to follow up with @tpetracca about the best approach here.

**Comment by nziebart** [comment]
So as I see it, the pros of endpoint-based registration are:
- Clients can create/destroy namespaces at will, with no config setup required
- No need for live-reload

Pros of config are:
- Easy to reason about
- No need for code changes in atlasdb to handle namespace-does-not-exist errors
- Probably fairly straightforward once we figure out live-reload in general

A couple questions around endpoint-based registration: 
- What is the benefit of explicit registration over implicit registration (i.e., just creating the namespace the first time it's requested)?
- Are there security concerns around clients potentially creating unneeded namespaces, causing excess resource consumption?

**Comment by jeremyk-91** [comment]
I believe this is fixed in #2252.
