### ISSUE TITLE
Flaky test: CommandLineEteTest

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1799]
All of the recent flakes in our internal oracle-driver builds are due to tests in this class. Going back over the past 36 builds (until I encountered a different flake):

multipleTimestampFetchesAreDifferent: builds 365, 357, 352, 350,  349, 335, 332 (flake rate ~20%)
sweepAllTablesDoesntError: builds 363, 345, 330 (flake rate ~9%)

Flakes in other classes:
TodoEteTest: 344 (flake rate ~3%)

Perhaps there's something in the provisioning/setup of the builds that makes the ETE tests flakier?

**Comment by SerialVelocity** [comment]
Looked into build 332 and it may be because:
 1. We are hammering the timestamp service (~100 timestamp requests per second per server) and all we're getting back are 503s... So most likely Paxos can't take place due to contention.
 2. It could also be AtlasDbEteServer#createTransactionManager creating lots of transaction managers.
 3. We're getting lots of transactionmanager warnings about failure to setup tables in Oracle. This means we aren't waiting for Oracle to start up properly
 4. Something else entirely

**Comment by rhero** [comment]
We really want to have oracle tests running pre-merge someday, and we wouldn't be happy with 1 in 3 tests failing due to flakes, so let's take a look this week.

**Comment by gsheasby** [comment]
Timeline of a failing test (internal 394):
```
10:51:32: Healthcheck kicks off
10:51:44: Healthcheck returns 500 (throwing FailoverFeignException) - this is reported in internal build 394, but is actually not the problem
10:51:45: ete-2 gains leadership and starts serving timestamps
10:51:45: Healthcheck returns 204
10:51:49.500: The CLI begins
10:51:49.694: Another leadership election (seq 3) somehow begins on ete-2
10:51:50.405: ete-2 reports that it has lost leadership
10:51:50: ete-2 returns 503 for a lot of fresh-timestamp calls (this is the CLI repeatedly trying to get a fresh timestamp)
10:52:00.401: After 10 seconds of this, the CLI output shows another FailoverFeignTarget "failover for too long" exception
10:52:05: ete-1 gains leadership (seq 6)
```

Timeline of a successful test (internal 395):
```
01:16:44: Healthcheck kicks off
01:16:53: Healthcheck returns 500 (on ete-1)
01:16:54: ete-2 gains leadership (seq 2) and starts serving timestamps
```

So the 500 / FailoverFeign exception is definitely a red herring. It looks like the second leadership election (combined with the lack of retry in the CLI test) is the problem.

**Comment by gsheasby** [comment]
"We are hammering the timestamp service (~100 timestamp requests per second per server) and all we're getting back are 503s... So most likely Paxos can't take place due to contention."

- yep, that is the healthcheck doing its thing. Perhaps if it did it less aggressively (trying once per second rather than 100 times), leadership election would be quicker.

**Comment by gsheasby** [comment]
The healthcheck verifies that it can get a fresh timestamp - however, `getFreshTimestamp()` itself goes through Feign's retry logic, which retries infinitely for 10 seconds, swamping the cluster.

The use of `FailoverFeignTarget` is hard-coded in [AtlasDbHttpClients](https://github.com/palantir/atlasdb/blob/0.40.1/atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java#L143) - in order to fix the flaky test, we would need to do one of the following:

a) Expose a `TransactionManagers.create` method that passed in a custom Retryer, and then pass in a Retryer that doesn't retry.

b) Expose some way to configure `FailoverFeignTarget` to effectively not retry (or not retry so excessively) - for example, by exposing Feign configuration settings as part of `AtlasDbConfig`.

c) Adjust `FailoverFeignTarget` to retry less aggressively (or with some kind of backoff). By default, this would affect all service calls.

As this is an ETE test, these changes would be visible to other products (although we might choose not to advertise them), and in particular, change (c) would affect all products.

However, we know that we have seen issues during leadership elections in the wild (including #383). So perhaps rather than making the ETE test artificially less aggressive, we need to make the cluster more resilient.

**Comment by fsamuel-bs** [comment]
After internal discussion, we're working with the following proposal to fix this behavior:

1. When there's a leader election occurring, the server throws a NotCurrentLeaderException, since it's not the current leader.
2. The client then proceeds to immediately query other timelock nodes for a timestamp.
3. After receiving NotCurrentLeaderException from all the timelock nodes in the cluster, the client should backoff (e.g. wait for 1 second) before re-querying the cluster nodes.

Note that the previous 2 steps are the current behavior. The fix add the third step to the retry logic.

**Comment by hsaraogi** [comment]
Fixed by #1939.

**Comment by fsamuel-bs** [comment]
CommandLineEteTest is still flaky. This seems to be because we're not correctly waiting for the service to startup before making the request, making the test fail with:
`com.palantir.atlasdb.http.FailoverFeignTarget: This connection has been instructed to fast failover for 10 seconds without establishing a successful connection. The remote hosts have been in a fast failover state for too long.`

In other tests of the same suite, it can be seen that we still have to wait quite some time for the server to handout the first timestamp request (sometimes for 8s). Correctly waiting for the service to startup or increasing the wait period at the start of each test seem to be the way to go.

**Comment by gsheasby** [comment]
Flake rate now seems to be about 25%
