### ISSUE TITLE
Clean shutdown should release its own background sweep lock

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#1816]
When the background sweeper is enabled, and you restart the Atlas-backed service, there's a reasonable chance that this will happen with the lock taken out.

Current behaviour: the lock remains taken out and must be manually released. This is not logged as an error (as it's expected for some workflows, and we don't notice that the same lock has been held for hours)

Desired behaviour: when the service is cleanly shut down, it commands the background sweeper to release its lock. If another client holds the lock, it should not be released.

**Comment by tpetracca** [comment]
Given we're running background sweep in the field now I'd argue this is a high priority issue.

**Comment by SerialVelocity** [comment]
Note: The shutdown hook should be set up before the CAS takes place so that if the CAS request fails (but succeeds behind the scenes) or the server is shutdown before we store the lock ID in an atomic ref, the lock is still released.

Also, do we want to do this just for sweep or for the lock in general? I just realised that since the backup lock release task must succeed for us, this lock could just be in memory instead of being persistent...

**Comment by tpetracca** [comment]
For correctness reasons it can't be in memory (at least in the client), because the client is potentially distributed.

**Comment by gsheasby** [comment]
Fixed by #1847.
