### ISSUE TITLE
Increase occurrence of leader elections

### ISSUE THREAD

**Issue by fsamuel-bs** [palantir/atlasdb#1930]
From @markelliot: since we've seen some issues when leader elections occur (e.g. #1749), let's make it happen more often so that we can detect if leader elections occur and if #1749 is fixed.

This will also force us to treat leader elections as first class citizens, instead of an edge case, resolving some quirks around it:

- #383 and its root cause, #1799 
- the cluster losing its locks when there's a leadership change.

_Make the unusual usual_

**Comment by jboreiko** [comment]
In particular this could be implemented simply by having each leader 'self-destruct' at some fixed period of time (say every 8 hours).  Self-destruction would take the form of refusing incoming requests as well as pings from other nodes (to induce a new election where the current node is not likely to win).  I'm not certain the second part is necessary but would make the leadership much more likely to round robin between the nodes instead of the same node just being reelected every 8 hours.

**Comment by hsaraogi** [comment]
Also, add more testing around leader elections during transactions.
