### ISSUE TITLE
Deprecate the Sweep CLI

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#1969]
This is a part of the work to deprecate command line scripts.
 - [ ] Have an endpoint to boost sweep priority for the background sweeper
 - [ ] Have an endpoint to sweep all or a particular table?

**Comment by tpetracca** [comment]
And in general I think we would do well to have the endpoint simply hook into core parts of the background sweeper code, and not have it's own impl (so we don't get current issues we have with sweep CLI because it's its own impl).

Ideally we'd get full equivalent functionality here:
- specify a table
- specify a 1-off start row
- specify 1-off batch sizes

**Comment by gsheasby** [comment]
A lot of the sweep code is reused (see SweepTaskRunner), but yes there are a few functional differences (e.g. stream store treatment) - tracked elsewhere.
