### ISSUE TITLE
Atlas Console put() is broken

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2070]
```
    private Map<String, Set> columnFields() {
        return this.getDescription()['columns'].inject([:]) { map, col ->
            (map as Map)[col['long_name']] = col['value']['type']['fields'].collect { field ->
                return field['name']
            }.toSet()
            return map
        } as Map
    }
```

But 'type' is a string e.g. `"VAR_LONG"`, so this won't have a fields property.

```java
groovy:000> x.put([row: ('version'.getBytes()), cols: [('version'.getBytes()): 3141592]])
No such property: fields for class: java.lang.String
```

Saw this internally when debugging with internal pencil deployment.

**Comment by tboam** [comment]
@kpurcell84 wondered if you were tracking this as part of your work on Console?  Would you be able to look into fixing this?

If not we can take a look but you have a lot more context on the problem.

**Comment by kpurcell84** [comment]
@tboam, interesting timing, I actually just discovered this when doing some testing last week. It seems like it's been broken for a long time.

A part of me wants to remove the put/delete functionality of Console all together, because it seems like giving people the ability to do db surgery in a non-programmatic way can cause more harm than good (especially in PG).

Do you have any opinions on whether or not we should keep it?

**Comment by kpurcell84** [comment]
@jeremyk-91, same question for you, what exactly were you using 'put' for when you ran into this issue?

**Comment by tboam** [comment]
The ability to do writes has proven useful in the past during support issues.  Where we need to edit values in the database directly this is quicker and safer to do via Console than either on csql (or similar) or writing an application using the TransactionManager API (which frequently doesn't allow the things we want to do).

So I would argue for keeping it, assuming we can actually fix it so it works.  Do you have an idea for the amount of work this would involve?

**Comment by kpurcell84** [comment]
Hmm I looked back in time and it seems like Console 'put' has been broken for at least a year, possibly longer. So that method of insertion has probably not proven useful during support issues (or anything else for that matter) for a while.

I haven't taken the time to dig into what fixing it would involve, but I don't think it would be incredibly difficult. The real problem is that I feel the feature is generally not a good idea. It doesn't take into account updating any indexes (despite what some documentation claims), and so I think that without a very deep understanding of the schema, you're more likely to screw things up by using it.

I talked to the internal Support team, and they were okay with getting rid of Console db modification because they said they never use it, and prefer to modify data programmatically if they need to in a support situation to ensure that the indexes are kept up to date.

I'm going to do a little more research into a couple internal product support issues that used Atlas _Shell_ to modify data in the past, to see if those situations could have been approached a different way. But as of now I'm still of the opinion that making Console read-only is the right way to go.

**Comment by kpurcell84** [comment]
Okay I talked to @hsaraogi today and she explained why it would be useful to have 'put' in AtlasConsole for PG deployments. Apparently not all Atlas schemas are not as complicated as the PG one, so my argument doesn't really hold up.

We should look into fixing the command. Also, it would be a really nice bonus if we added a flag for disabling db modification commands ('put' and 'delete'), which we could use to turn them off in PG.
