### ISSUE TITLE
KVS migration fails in the validation stage for sweep.priority table

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2137]
This causes some confusion when running the migration. The failure occurs as kvs migration writes to the `sweep.priority` in the `fromDatabase` but not in the `toDatabase`. This is not an issue in the migration stage but in the validation stage. One solution will be to bypass sweep tables when validating.

Ideally, we dont want to migrate the `sweep` namespace at all.

**Comment by fsamuel-bs** [comment]
Pinging @tpetracca, which apparently has fixed this previously. But we can also do this, since it seems small.

**Comment by tpetracca** [comment]
I did it in a hacky way a long time ago https://github.com/palantir/atlasdb/pull/1129/files
There's probably a better way; I wasn't sure if there would be other things impacted by that change.

**Comment by schlosna** [comment]
We just hit this doing a KVS migration and based on conversation with @twilson-palantir I think we do want to migrate the sweep tables as they have important metadata for sweep prioritization and progress tracking used by the sweep job; however, we want to exclude the sweep tables from validation step because the destination KVS will have updated at least the sweep priority table as a side effect of doing the KVS migration writes itself. 

One option might be to effectively overwrite the sweep tables at the very end of migration so that the destination KVS matches source KVS.

**Comment by schlosna** [comment]
We also currently fail the entire validation on the first error, while it would be useful to continuing to validate all tables. Would also be nice to allow users to specify validation of specific tables so you don't need re-validate all tables.

**Comment by schlosna** [comment]
While I'm at it, the current default migration logging seems quite verbose and can actually be a migration performance bottleneck due to I/O blocking the migrator threads as it doesn't seem to be using the async logger either.

**Comment by titatoverheks** [comment]
Files resumability and failing upon first error as a separate issue: https://github.com/palantir/atlasdb/issues/2200
