### ISSUE TITLE
KVS migration is not fully idempotent

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2240]
(See internal ticket 54990)

At the start of the KVS migration, we pre-commit the migration timestamp (which is a fresh timestamp from the source services), and then fast forward the destination timestamp to the current source timestamp. During the migration, we execute transactions against the destination, to update the checkpoint table. Because of this, if the migration is restarted, the source timestamp will likely be behind the destination, which can cause the pre-commit to fail.

A possible fix here would be to first fast-forward both services to the max timestamp of the two (before fetching the migration timestamp).
 
@tmgordeeva @jboreiko would appreciate a quick sanity check that the above makes sense

**Comment by jboreiko** [comment]
Discussed in person, looks like this problem is real.  Appears we don't hit it frequently as we do reads to the chechpoint table (thereby consuming timestamps that aren't written into the tx table).  There are a variety of solutions to work about the different logic required depending on whether you are restarting a migration from scratch vs. carrying on an existing one.  A good starting point is removing the logic in getMigrator() which does the precommit into the destination db :(

**Comment by fsamuel-bs** [comment]
Tagging @gsheasby for SA.

**Comment by sandorw** [comment]
@gmaretic, mind taking a look at this ticket and closing it if it's already addressed?

**Comment by gmaretic** [comment]
This has been fixed by https://github.com/palantir/atlasdb/pull/3587
We now first fast forward the destination timestamp, then take fresh timestamps in the destination for the migration and commit TS. That way, if we have progressed farther, the fast forward is a noop, but we still use greater timestamps than ever before. This does make it imperative to do the migration offline though, as it would otherwise be possible to migrate an inconsistent view.
