### ISSUE TITLE
Oracle compact internally might be able to SHRINK SPACE on Non-EE

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2262]
We might be able to use `SHRINK SPACE` to avoid the table bloat on Non-EE instead of logging a message which noone notices. This has caused disks to fill up at a deployment bringing the world to a stop as the DB could not be written to(PDS-55840). The solution was to add disks and run `SHRINK SPACE`. 

@clockfort for SA.

The code in question:
```
    @Override
    public void compactInternally() {
        if (config.enableOracleEnterpriseFeatures()) {
            try {
                conns.get().executeUnregisteredQuery(
                        "ALTER TABLE " + oracleTableNameGetter.getInternalShortTableName(conns, tableRef)
                                + " MOVE ONLINE");
            } catch (PalantirSqlException e) {
                log.error("Tried to clean up {} bloat after a sweep operation,"
                        + " but underlying Oracle database or configuration does not support this"
                        + " (Enterprise Edition that requires this user to be able to perform DDL operations)"
                        + " feature online. Since this can't be automated in your configuration,"
                        + " good practice would be do to occasional offline manual maintenance of rebuilding"
                        + " IOT tables to compensate for bloat. You can contact Palantir Support if you'd"
                        + " like more information. Underlying error was: {}", tableRef, e.getMessage());
            } catch (TableMappingNotFoundException e) {
                throw Throwables.propagate(e);
            }
        }
    }
```

**Comment by clockfort** [comment]
Looks good. I had two fears that I looked into:

- Locking pattern (the thing we were originally avoiding here in EE vs non-EE is an exclusive table lock during which the entire table is read in and written back down, which is far too long to hold an exclusive table lock!) 
According to http://www.oracle.com/technetwork/issue-archive/2005/05-may/o35tuning-096075.html , you can issue `shrink space compact` (which only needs row-level locks, so that's fine) and `shrink space` afterwards (which needs an exclusive table lock to change the high water mark, but hopefully won't take too long)

- According to several sources, shrink space isn't compatible with indexes, which made me fear that it wasn't appropriate for IoT tables like ours, but after really looking into it, I think what people really mean to say is that the compaction phase doesn't preserve index references very well when it moves the data around, which makes much more sense. Because we don't have external indexes, I think this should work fine.

I think we should do this, and remove the separate enterprise path, which actually does slightly less compaction work than `shrink space` does. I also think that we should do the second SQL statement with a timeout, so we can just give up if we don't grab the lock in a minute or two on a busy table.
