### ISSUE TITLE
Random TimeLock Stuff

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#2274]
// this is based off of testing the HEAD of the `feature/timelock-agent` branch.

- The first time you fetch a timestamp for a client for the first time since bouncing that node, you get an exception. Subsequent curls (to the same uri) work.
```
{
    "exceptionClass": "com.palantir.leader.NotCurrentLeaderException",
    "message": "method invoked on a non-leader",
    "stackTrace": [
        {
            "className": "com.palantir.leader.proxy.AwaitingLeadershipProxy",
            "fileName": "AwaitingLeadershipProxy.java",
            "lineNumber": 204,
            "methodName": "notCurrentLeaderException"
        },
        {
            "className": "com.palantir.leader.proxy.AwaitingLeadershipProxy",
            "fileName": "AwaitingLeadershipProxy.java",
            "lineNumber": 209,
            "methodName": "notCurrentLeaderException"
        },
        {
            "className": "com.palantir.leader.proxy.AwaitingLeadershipProxy",
            "fileName": "AwaitingLeadershipProxy.java",
            "lineNumber": 147,
            "methodName": "handleInvocation"
        },
        {
            "className": "com.google.common.reflect.AbstractInvocationHandler",
            "fileName": "AbstractInvocationHandler.java",
            "lineNumber": 84,
            "methodName": "invoke"
        },
        {
            "className": "com.sun.proxy.$Proxy54",
            "fileName": null,
            "lineNumber": -1,
            "methodName": "getFreshTimestamp"
        },
        ..... many more things ......
   ]
}
```
- We should explicitly log that we're creating a new client when we do (and what the client name is? not sure if this is safe or not). At the moment the only log lines I get are:
```
INFO  [2017-08-17T21:47:47.357Z] com.palantir.atlasdb.timelock.paxos.PaxosSynchronizer: Started up, and no one I talked to knows anything yet.
INFO  [2017-08-17T21:47:47.362Z] com.palantir.timestamp.DebugLogger: Creating PersistentTimestamp object on thread {}. If you are running embedded AtlasDB, this should only happen once. If you are using Timelock, this should happen once per client per leadership election (threadName: AwaitingLeadershipProxy.java:86-0)
INFO  [2017-08-17T21:47:47.362Z] com.palantir.leader.proxy.AwaitingLeadershipProxy: Gained leadership for {} (leadershipToken: PaxosLeadershipToken{PaxosValue{data=null, leaderUUID='6a02e71f-2098-425a-a088-41c365a194a2', seq=0}})
```

edit: clarify first bullet happens for all clients once each after node restarts (and not for "new" clients)

**Comment by jeremyk-91** [comment]
Regarding the first issue: this is a race condition between the AwaitingLeadershipProxy's create step where it grabs a leadership token from the leader election service and sets its local `tokenRef` to point to that, and its check that the token reference is not null when a method is being called. It's benign, since 503 in practice means that clients will retry.

This can be fixed in several ways, such as maintaining a central `AtomicReference<LeadershipToken>` or wrapper around such (though there are some concurrency related complications in `AwaitingLeadershipProxy`). However, I think the eventual fix isn't actually breaking, and so there's no harm getting a fix in post-GA.

I agree we should do the logging. Client name should be safe given that users do not have access to timelock directly, and only access it through other Palantir products for which client names are known beforehand.

**Comment by fsamuel-bs** [comment]
Testing on an internal stack: can confirm that TimeLock throws a NotCurrentLeaderException when creating the client.

**Comment by fsamuel-bs** [comment]
When fixing this issue, we should also update our internal "how to deploy timelock" docs, since some of the steps there won't be needed anymore in versions with this fix.
