### ISSUE TITLE
Don't output the stacktrace for WARN logs on timeouts to C* nodes

### ISSUE THREAD

**Issue by ashrayjain** [palantir/atlasdb#2280]
Based on feedback from folks.

**Comment by clockfort** [comment]
If the stack traces are for a thread that actually has the honest-to-goodness operation on it (e.g. tells you that this timeout was caused by a getRanges() or inside of sweep, etc) I would consider them useful.

If the stacktraces are all just identical and only encompass the stack from a cassandra internal threadpool thread or something, then I agree that they are useless and should be removed.

**Comment by hsaraogi** [comment]
@ashrayjain do you have an example stacktrace here?
