### ISSUE TITLE
AtlasDB KVS intrumentation does not record metrics for getRangeOfTimestamps

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2426]
The metrics for `getRangeOfTimestamps` seem to be missing when looking at metrics in the internal data ingestion tool. We should check why these are not being reported.

This method will help measure sweep performance.

**Comment by fsamuel-bs** [comment]
In a recent stack, by hitting the metrics endpoint, I've noticed that we just record:
```
    "com.palantir.atlasdb.keyvalue.api.KeyValueService.createTable" : {
    "com.palantir.atlasdb.keyvalue.api.KeyValueService.createTables" : {
    "com.palantir.atlasdb.keyvalue.api.KeyValueService.get" : {
    "com.palantir.atlasdb.keyvalue.api.KeyValueService.getAllTableNames" : {
    "com.palantir.atlasdb.keyvalue.api.KeyValueService.getMetadataForTables" : {
    "com.palantir.atlasdb.keyvalue.api.KeyValueService.getRange" : {
    "com.palantir.atlasdb.keyvalue.api.KeyValueService.getRows" : {
    "com.palantir.atlasdb.keyvalue.api.KeyValueService.put" : {
    "com.palantir.atlasdb.keyvalue.api.KeyValueService.supportsCheckAndSet" : {
```

We're probably filtering the other ones out.

**Comment by fsamuel-bs** [comment]
Actually... I think we don't filter anything out. The service I was using to look at the metrics doesn't use all the methods on the KVS api, which makes it not record metric for some methods.

Also, we don't see `getRangeOfTimestamps` because the only place it is called is when we do `getCandidateCellsForSweeping`. Our codepath looks like:

```
SweepTaskRunner.doRun ->
InstrumentedKVS.getCandidateCellsForSweeping ->
CKVS.getCandidateCellsForSweeping ->
CKVS.getRangeOfTimestamps
```

Since `getRangeOfTimestamps` doesn't go through an instrumented kvs, we don't register metrics for it. But this is fine, as we have the `getCandidateCellsForSweeping` durations, which is what we care about here.
