### ISSUE TITLE
Deprecate transaction manager creation methods that don't specify user agents

### ISSUE THREAD

**Issue by nziebart** [palantir/atlasdb#2528]
Currently some overloads of `TransactionManagers#create` do not require a user agent, and thus use the default ("unknown-atlasdb"). There's no reason users should use these, so we should deprecate/discourage/delete these methods

**Comment by tpetracca** [comment]
So state as of #2459:
- all `create` methods are deprecated
- the builder optionally allows for a few ways to specify the [user agent](https://github.com/palantir/atlasdb/blob/develop/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L142-L150), which were chosen explicitly because they matched the existing power of the api of the various `create` methods. I'm more than happy to just break that immediately and make it mandatory to directly specify the user agent when you're using the builder (given that it's brand new and thus not really a break; I guess we've released since then, but **shrug**)

**Comment by hsaraogi** [comment]
User agent should be required when creating the TM.
