### ISSUE TITLE
Multiple schema mutation lock tables

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#2583]
Before timelock, we used to enforce that the lock leader creates the _locks schema mutation lock table if the config has a leader block. 

But now, every node in a HA service believes that they are the lock leader and create a schema mutration lock tables after checking if one already exists, thus presenting a race condition.

This race condition has been hit in the field quite a few times and the solution we have currently is to drop all _lockUUID tables manually and restart the service (hoping it doesnt hit the race again)

This presents a case where manual action is necessary and we can't automatically rollback or move forward.

One possible solution here is to always create _locks table and depend on Cassandra's `createIfNotExist` to ensure multiple tables are not created. Note: currently the lock table is called `_lockUUID`.

**Comment by tpetracca** [comment]
`CREATE TABLE IF NOT EXISTS` doesn't give you the concurrency guarantees you need here.

**Comment by gmaretic** [comment]
Why did we go with _lockUUID in the first place?

**Comment by fsamuel-bs** [comment]
`CREATE TABLE IF NOT EXISTS` doesn't work, unless we backported it to our internal version of Cassandra. @tpetracca you even commented on the [thread](https://issues.apache.org/jira/browse/CASSANDRA-10699). Oo

Quoting this other related [thread](https://issues.apache.org/jira/browse/CASSANDRA-10776):
```
The IF NOT EXISTS for DDL is actually not useful to prevent concurrent creation, it's only a convenience when you know the table may pre-exist, which is mostly useful for testing purposes to be honest.
```

**Comment by fsamuel-bs** [comment]
Finally found the initial ticket that started the schema mutation lock discussion: #444. I think that we didn't go for _lockUUID because we needed service to be initialized first to take locks, since we were running embedded at that time. Now, I think we can go with the `_lockUUID` solution when the `timelock` block is present on the client side.

**Comment by tpetracca** [comment]
@fsamuel-bs yea they haven't even resolved the issue yet; not to mention the fact that it's going to be too invasive to backport. For the time being I think we need to accept that we have to solve this issue on our side.

Yea the _lockUUID method was so that multiple clients can create their own lock table at the same time without fear of triggering the bug on the lock table creation.

Yea we should figure out how we can get away with using a LockServer lock for this. Would have the added benefits of removing a persisted lock that we don't have great tooling around clearing in an SSH-less world.

**Comment by gsheasby** [comment]
@chrisalice has a truly marvellous algorithm to fix this issue, which this margin is too narrow to contain.

Whoever has bandwidth to pick this up should grab a whiteboard and talk to her about it.

**Comment by gsheasby** [comment]
We should use timelock and take one of its locks in order to avoid creating multiple tables.

**Comment by chrisalice** [comment]
Aren't those advisory?

Joe suggested having the timelock service create a bootstrap table and
using that somehow...

**Comment by gsheasby** [comment]
If we use the timelock lock to create the `_locks_uuid` table, then this is good enough except when timelock goes down or has a leadership election while we're starting a service for the first time.

Even then, we'd need to have node A take the lock and create a table, and then have a leadership election followed by node B taking the lock from a new leader before node B sees that node A has created a table.

So taking a timelock lock would be reasonably low-lift and would get us to a better situation (contention is less likely) but not quite 100% of the way there.

Having the timelock service create a bootstrap table would be a larger task. It would reduce the problem to "how to ensure that timelock only creates one bootstrap table", where one failure case would be "timelock node A gets elected, sends a call to create a bootstrap table, then dies; then timelock node B gets elected fast enough that it doesn't see the bootstrap table that node A told Cassandra to create". Since timelock is already deployed, another failure case would be "timelock has no bootstrap table and a new service comes online, causing timelock to create a bootstrap table, and then while that happens a leadership election occurs...."

**Comment by gsheasby** [comment]
Does this approach get the failure probability asymptotically close to zero?

When a node starts up:
1. If there is one `_locks` table, done
(Assume no `_locks` table)
2. take a timelock lock
3. create a `_locks` table
4. check the lock is still valid
5. if valid, done
6. if not valid, delete the `_locks` table, wait e.g. 5 seconds, and go to 1.

**Comment by alxhill** [comment]
Was a solution ever found to this? Hit on Beta Prod deploying Automator.

**Comment by gsheasby** [comment]
The plan above should drastically reduce the incidence of the issue - we're hoping to get to it soon.

**Comment by chrisalice** [comment]
I'm worried a table can get picked up by a node and before it is deleted by its creator. What is the behaviour in this case?

**Comment by gsheasby** [comment]
Do you mean this scenario?
1. There is no `_locks` table
2. Node A comes online and takes a timelock lock
3. Node A creates `_locks_A`
4. Node A goes to sleep and loses the lock
5. Nodes B&C come online and see `_locks_A`
6. Node B takes a lock in `_locks_A` for creating tables
7. Node A wakes up, sees that its timelock lock is invalid, and deletes `_locks_A`

In this case, Node B has a Heartbeat thread that is regularly updating the value in `_locks_A`. Further updates will fail, causing this thread to throw exceptions.
If step 7 happens after the last beat, then `SchemaMutationLock.schemaMutationUnlock()` will fail, causing e.g. the table creation to throw an exception _**and metadata not to be created**_

To make the approach more bullet-proof, step 6 in my above post can be "if not valid, read the value in the `_locks` table. If this value indicates someone else holds the lock, and there is no other lock table, then we're done".

**Comment by alicederyn** [comment]
1. There is no `_locks` table
2. Node A comes online and takes a timelock lock
3. Node A goes to sleep and loses the lock
4. Node B comes online and takes the timelock lock
5. Node B creates _locks_b
6. Node C takes a lock in _locks_b
7. Node A comes online and creates _locks_a before going to sleep again
8. Node D takes a lock in _locks_a
9. Nodes C + D corrupt each other and commit without ever realising.
10. Node A wakes up and deletes _locks_a

**Comment by gsheasby** [comment]
I was just typing a very similar case. We're actually OK in your case, because Node D will not take a lock in _locks_a.

If Node D comes online at step 8, then it will try to get the only lock table, but fail, because there will be two tables at this point. In this case, we should make node D sleep and try again in some number of seconds.

Failure case there is if Node A never wakes up to delete its table; running the clean locks state endpoint should fix things up.

**Comment by alicederyn** [comment]
Ah, I missed that the table names would be unique and hence nodes can see all of them. That seems good then.
