### ISSUE TITLE
Mark stream store tables as safe for logging by default

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#2789]
Stream store tables are not created dynamically, and we have control over what the table names are (except for the prefix), and what the row names and column components are.

We should mark these as safe for logging by default, and call it out in the release notes, so that any product that does turn out to have an unsafe stream store table name can opt out of log safety.

**Comment by tboam** [comment]
I disagree with this.  Assuming data is safe unless told otherwise is the opposite of our normal set up and adds considerably more risk.

I'd prefer we continue to treat as unsafe and require products to declare things as safe.  To deal with the issue of products not doing this and useful logging being lost we should send out a reminder to all internal teams to mark things as safe and include it in our docs.

**Comment by gsheasby** [comment]
OK - but we should still provide _some_ way to mark stream store tables as safe for logging, since this is currently impossible.

**Comment by tboam** [comment]
Yeah, we should. Sorry, I thought this was just changing the default, didn't realise it is currently impossible

**Comment by gsheasby** [comment]
(for tracking) replaced by #2801
