### ISSUE TITLE
Enable asynchronous initialization by default

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#2841]
Should we change the default value for asynchronous initialization to true?

**Comment by gsheasby** [comment]
I would like to see this done and tested for our internal storage product, before rolling it out to all products.

**Comment by hsaraogi** [comment]
We cant enable it by default in AtlasDB due to concerns with the large internal product.

**Comment by tpetracca** [comment]
Can't we just give them the override?

**Comment by gsheasby** [comment]
The argument was that we can't be sure that we would apply the override correctly in all places. Also there is no "them" to give it to any more, as there is no longer a large internal product sub-team dedicated to AtlasDB. So we'd own any problems that we cause 😿

**Comment by tpetracca** [comment]
> The argument was that we can't be sure that we would apply the override correctly in all places.

Because of atlasdb or because of it?

> there is no longer a large internal product sub-team dedicated to AtlasDB. So we'd own any problems that we cause

This isn't really a reason. There are still a number of people who understand that ecosystem very well that we could leverage and it really shouldn't be all that hard.

---

The trade-off of not doing this is increased 1-off non-default configurations across 95% of our internal atlasdb clients.
