### ISSUE TITLE
Improve docs on sweeping through the sweep endpoint

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#2950]
The docs http://palantir.github.io/atlasdb/html/cluster_management/sweep/sweep-endpoints.html are a bit lacking, and we had to go check out the code to verify that you need to send a POST request and that the table name is a query param. Adding an example and a few more sentences would be helpful.

**Comment by gsheasby** [comment]
The docs should also warn in big red letters that running the command with `-k` and adding params with no quotes will result in a full sweep silently kicking off for that table in the background. Or they should at least instruct users to check the logs after kicking off the command to verify that sweep is running and whether the parameters seem correct.

We may also want to warn that once started, the sweep cannot stop unless the service is restarted.

We had a case this week of a user accidentally having 12 sweeps running concurrently due to malformed commands.

**Comment by jeremyk-91** [comment]
#2980 merged
