### ISSUE TITLE
CassandraService.getRandomHostByActiveConnections() can throw

### ISSUE THREAD

**Issue by gmaretic** [palantir/atlasdb#3041]
Because all hosts can get filtered out

**Comment by gsheasby** [comment]
This should never happen - the method is used twice, but in both cases, the filter is a non-empty subset of the current set of hosts. There isn't sufficient guarding at the moment, though, because a lot of methods went from private to public during a refactoring a couple of months ago.

Since we don't want to throw even in the case of programmer error (i.e. someone breaks the currentPools/tokenMap relationship), I can change the method to return an optional, and when it's used, default to a random host if the optional comes up empty.
