### ISSUE TITLE
If one Cassandra node is down, BackgroundSweeper spams ERROR logs

### ISSUE THREAD

**Issue by fsamuel-bs** [palantir/atlasdb#3054]
We require consistency ALL when deleting values. When we have a quorum of nodes up and BackgroundSweeper is enabled, BackgroundSweeper will constantly try to delete and spam ERROR logs while doing so, since Cassandra will throw an UnavailableException.

**Comment by tboam** [comment]
We can reduce the logging level to WARN and confirm that Sweep alarms allow a suitable window for the problem to be resolved.

**Comment by sandorw** [comment]
Looks like Cass must not be throwing the `InsufficientConsistencyException` here: https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweeperImpl.java#L232. If that gets thrown, we don't log at error.

Also, if `runOnce()` throws a `RuntimeException` (which `UnavailableException` is), it should be caught.

**Comment by gsheasby** [comment]
The cass layer _does_ throw `InsufficientConsistencyException`, e.g. from [here in the read stage](https://github.com/palantir/atlasdb/blob/0.79.1/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/paging/RowGetter.java#L67).

The ERROR logs actually come a layer deeper, from the [CassandraClientPool retry logic](https://github.com/palantir/atlasdb/blob/0.79.1/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraRequestExceptionHandler.java#L106) - this appears every few minutes, when sweep tries and fails to read at consistency ALL.

In this case, the error messages generated noise that distracted from diagnosing the real issue. When nimbus comes into play, these errors will appear on the nimbus logs rather than in the service logs.

It might be that as a library, Atlas should not log errors in this situation, as we don't know whether this request failing is something dire enough that we should [wake someone up to look at it](https://labs.ig.com/logging-level-wrong-abstraction).

I think we should **downgrade this ERROR to a WARN**, as the product should be responsible enough to log ERRORs if it cares about its query failing. I imagine that products will log errors if they can't write to Atlas, anyway.

Tagging @sandorw and @tboam for thoughts.

**Comment by sandorw** [comment]
That seems reasonable. Sweep doesn't need to log loudly if a Cassandra node is down, since Cassandra  metrics should be diagnosing that. Similarly, the product's logs and metrics should show if read/write requests are consistently failing. At the very least, the product will be logging the exceptions here.
