### ISSUE TITLE
Prevent txns with timestamps too early to be possible

### ISSUE THREAD

**Issue by tkleingarn** [palantir/atlasdb#3120]
Internal ticket where this came up: PG-114996 "factory product stacks installed in same stack as dispatch cause dispatch to fail due to timelock". There are cases where a deployment may run TimeLock and all services for _factory_ and _large (LIP)_ in a single stack managed by the same tool. This is a common configuration in the field.

LIP now supports the use of an external TimeLock service. In the ticket referenced, because it was part of the same stack, dispatch automatically discovered and connected to Factory's TimeLock instead of its legacy lock server.

1. If Factory's TimeLock issued a transaction timestamp that is higher than the maximum commit timestamp in Dispatch's KVS, this would not be a problem.
2. If Factory's TimeLock issued a transaction timestamp that is lower than the maximum commit timestamp in Dispatch's KVS, we have a problem. I believe this could result in a successful writes to the KVS with a commit timestamp earlier than the most recent commit. That would mean dispatch is writing "ghost data" to it's KVS that will never be read in a future transaction (devs please confirm, I may be misstating this).

I think we need to guard against case 2. Is it possible to cause a transaction to immediately fail if its start timestamp is "too early" and violates the transaction protocol?

**Comment by jeremyk-91** [comment]
Yep. 1 is perfectly safe; case 2 can break Atlas in a ton of ways (one way is what you describe, but you can also have other scenarios like getting the same start timestamp as another txn, getting rolled back, but your writes actually living on as though they were written by the real txn).

We actually already have a checking mechanism (see #3018). It's not as precise as getting the maximum commit timestamp (that can be tough because we don't have an index on commit ts in the transactions table), but it's not too distant of an approximation. We check a fresh timestamp against the punch table (wall clock time up to 1 minute ago -> ts). However this only runs in TM.create and I'm aware we also create the TM a different way - we could consider adding this mechanism to the other creation path

**Comment by tboam** [comment]
@tkleingarn ping

**Comment by sandorw** [comment]
Closing out, as it's been hooked up internally.
