### ISSUE TITLE
Non-canonical sort of getRows response

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#316]
Our Resource Store runs on AtlasDB and when performing certain transactions (specifically, getRows), we’d like to have the RowResults returned in the order that they were passed in as parameters. Unfortunately, the Transaction interface has a return value of SortedMap, which sorts the RowResults by their primary feature (in this case ResourceIdentifiers). On our end, this results in a server-side resorting of the returned results, which is not the end of the world per se but it’s a bit redundant. Would be great if there were a method that returned the list of results in the same order they were passed in.

**Comment by pearsonhenri** [comment]
awesome! will be great to have this

**Comment by schlosna** [comment]
This seems relatively straightforward to implement as a utility to transform the results rather than modifying the `com.palantir.atlasdb.transaction.api.Transaction#getRows` API itself. Providing this at the transaction level could have significant impacts depending on the how the backing KVS returns results, and in many cases the result map ordering is necessary for clients.

**Comment by joelea** [comment]
This sounds like it's not a good risk-reward tradeoff given other priorities, so will be closing this for now - please let us know if you think we're underestimating the importance of this issue.
