### ISSUE TITLE
Missing test coverage: failed put unless exists during commit

### ISSUE THREAD

**Issue by sandorw** [palantir/atlasdb#3175]
See https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java#L1969, which passes in a null TableReference, which causes a logging NPE in the `getCommitTimestamps` method. This means that we have no test coverage for transactions where the `putUnlessExists` call throws a `KeyAlreadyExistsException`.

**Comment by felixdesouza** [comment]
I believe this has been fixed by #3205, however looking at what's in develop, the parameter doesn't seem to make sense. We only use it for metrics. Why even have it at all? We're not doing different things based on the table reference i.e. if rest of the arguments remained the same, nothing would change. My only guess is that we're looking for timestamps in the context of a particular table, but the timestamp store itself doesn't know/care about tables.
