### ISSUE TITLE
Lock Test reported incorrect ordering, should not flicker

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#366]
The build with the failing test can be found here.  It cannot be consistently reproduced.  https://circleci.com/gh/palantir/atlasdb/141

**Comment by clockfort** [comment]
Vaguely related https://jira.yojoe.local/browse/QA-94253

**Comment by clockfort** [comment]
( I know, not same test, just indicating other things in this test suite also stink )

**Comment by gsheasby** [comment]
The fix for 94253 appears to have been to bump up some wait times to avoid the slower build servers tripping the test. (PR here: https://github.com/palantir/atlasdb/pull/395)

In the failure linked above, it appears that the write lock thread took too long (10ms < timeTaken < 20ms) to grab the lock, and so the read lock thread grabbed it first, which is why we get "two, one, two" instead of "one, two, two".

**Comment by jboreiko** [comment]
Closed as fix is in at #559
