### ISSUE TITLE
Logging doesn't work as expected if multiple TransactionManagers are used

### ISSUE THREAD

**Issue by diogoholanda** [palantir/atlasdb#3834]
`LoggingArgs` keeps a static reference to a `KeyValueServiceLogArbitrator logArbitrator`, which is "hydrated" at TransactionManager initialization. This hydration process overrides any previous hydration from previously initialized TransactionManager.

Ideally, `LoggingArgs` would not be static. Another alternative, faster to implement but in my mind less ideal, would be to make the hydration process be cumulative, rather than override any previous run of it.

**Comment by diogoholanda** [comment]
@a-k-g for SA

**Comment by jeremyk-91** [comment]
Yep, that's fair - when this was initially written it assumed 1:1 mapping between services and Atlas TMs, though in hindsight that was a pretty big assumption.

Cumulative approach sounds good, though there is an issue with conflicts (because generally when you call `LoggingArgs` you only have a `TableReference`), if in one service you have 2 TMs accessing different keyspaces, and you have tables named the same way where the safety of a component differs (e.g. TM1 accesses `tm1.default__data` which is marked as safe and TM2 accesses `tm2.default__data` which is marked as unsafe). I guess defaulting to unsafe is probably the best we can do there, though that could be a decent start.
