### ISSUE TITLE
As a developer I want a standard place to persist metadata about a cluster to avoid different processes using different settings

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#410]
This is primarily to allow KVS migration to store the target KVS.

**Comment by tpetracca** [comment]
Biiiiig +1 to this

**Comment by joelea** [comment]
Do you need this for a particular feature?

**Comment by tpetracca** [comment]
No, though eventually I think we'll want it to be able to support multi-DC cassandra and hot failover in case of losing a DC, but isn't a priority.

I've just time and time again disliked how'd hard some of the kvs startup things are to grok or read because we don't keep state around the cassandra cluster.

**Comment by joelea** [comment]
Ah, that's another good reason to do this that I hadn't thought of. We should definitely do this as part of the KVS clean up work (e..g #407)

**Comment by rhero** [comment]
Since supporting an online KVS migration isn't a high priority, we're not going to address this anytime soon.
