### ISSUE TITLE
As a consumer of Atlas I don't want the Atlas Version to be printed to System.out

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#442]
We've had a couple of people confused by this, we should find a more sensible place to log it.

**Comment by jboreiko** [comment]
@mglazer can you remind us of the justification here.

**Comment by mglazer** [comment]
Basically, it was the easiest possible way to ensure that metrics collectors like relay could find and report on the AtlasDB version for a product, so that we could quickly collect the versions used across products.

However, it ended up being easier for the implementors to just search for META-INF/atlasdb.version and grab that. So sending you a PR to remove this functionality.

**Comment by rhero** [comment]
Closing out per Glazer's comment.
