### ISSUE TITLE
AtlasDB not robust to InterruptedException

### ISSUE THREAD

**Issue by kbrooun** [palantir/atlasdb#4445]
Looking at the code for atlasdb: https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/CellsSweeper.java#L89 there is a possibility that the persistent lock could be acquired, but the thread interrupted before the try-finally block is entered https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/CellsSweeper.java#L92. This would leave the persistent lock still in the database.

**Comment by jkozlowski** [comment]
I don't think that code in CellsSweeper is necessarily incorrect: it is the PersistentLockManager that should potentially be a bit more careful? CellsSweeper is implemented correctly: in order to get an interrupted exception, your thread must be in a particular state (i.e. currently suspended in a call that can receive it). I don't believe arbitrary code can throw. And as soon as persistentLockManager.acquirePersistentLockWithRetry(); returns, we enter a try-finally.

In https://github.com/palantir/atlasdb/blob/develop/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/PersistentLockManager.java#L113,  the only thing that's a bit meh is that we log some stuff which technically could throw and thus leak.

**Comment by GrahamDennis** [comment]
OK, sounds like we would need an actual stack trace for the original problem to reproduce.  Feel free to close out.
