### ISSUE TITLE
Client recovery after leader switch can fail

### ISSUE THREAD

**Issue by Jolyon-S** [palantir/atlasdb#4471]
Refer to internal PDS-107023

**Comment by felixdesouza** [comment]
Leader election seems fine

timelock 2 became the leader at 9:22:18.9
timelock 3 became the leader at 9:24:15.8
timelock 1 became the leader at 9:25:35.2

at 9:24:15.0, request comes in to internal product, fails at 9:24:29 with 503. 

503s aren't thrown via atlas remoting when using conjure, we believe it's when the node is shutting down that 503s are thrown.

We effectively retried 11 times for around 15 seconds, and the last request happened to fall on timelock 1 which was in the process of shutting down. Unclear whether we were always hitting timelock 1 throughout this request, but we should have hit other nodes as timelock 2 had been elected leader and timelock 1 wouldn't become the leader for another minute or so.

As an aside, `stepDown` doesn't get invoked before the server closes connections meaning other nodes gain leadership before the node can step down => no op.

**Comment by felixdesouza** [comment]
Ultimately, to avoid this loop which happens 0.05% of the time, we need to pass the url of the actual leader through to the 308.

CJR behaviour on 503 marks the request as successful - so doesn't blacklist the node - but switches to the next node in the ring. 

Although this doesn't really help us here because the node being shutdown never 308s nor does it 503 to itself, so we can only arrive here by being redirected via a 308 on a follower, which does not respect blacklisting logic.

**Comment by felixdesouza** [comment]
In #4472, we've increased the 503 retries to 13, so the probability is around 0.012%.

**Comment by felixdesouza** [comment]
As an FLUP, pending lifecycle changes, we want to still mark ourselves as ineligible to prevent a shutting down node from participating in leader election. However, I'm not convinced that stepping down buys us anything, if anything it might make things slower since you'll potentially do two paxos rounds. i.e. Propose anonymously, and then the other nodes do their own proposal.

You could potentially propose the uuid of another node, although it's probably easier to just let the followers do it since we ping 20 times a second by default.
