### ISSUE TITLE
After doing a put, putUnlessExists will succeed.

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#613]

**Comment by rhero** [comment]
For context, this is because putUnlessExists (PUE) uses timestamp 0 whereas put grabs the latest timestamp. Tables that only use PUE, like the timestamp table, will work fine. Other tables that may use puts and PUE will not behave as users might expect, i.e. after doing a put, PUE will succeed and the put value will be the one that is read.

**Comment by clockfort** [comment]
we could fix this by putting a piece of table metadata down similar to .supportsRangeScans(), called .supportsPutUnlessExist(), and have (normal) puts to this table fail? Would require a table metadata caching layer, but this seems easy enough.

**Comment by joelea** [comment]
Another option I've been thinking of is changing putUnlessExists to have the same signature as put, and explicitly state the sentinel were using elsewhere.

**Comment by gsheasby** [comment]
Why don't we want to make tables work as expected with both put and PUE, by making PUE do a more rigorous check?

**Comment by joelea** [comment]
The issue as I see it is that there's no "as expected behaviour" for `putUnlessExists(key, value)` at the KVS layer as everything is so dependent on timestamps. For a transaction it makes sense, you just use the transaction timestamp. However, it would also end up being a read then a write inside a transaction.

**Comment by gsheasby** [comment]
We're unlikely to get to this - closing.
This is only an internal-facing issue, as it only affects people who interact with the KVS directly.
