### ISSUE TITLE
Document possible recovery process from MultipleRunningTimestampServices error

### ISSUE THREAD

**Issue by joelea** [palantir/atlasdb#614]
(TODO @gsheasby @rhero @jboreiko - figure out a BLUF)

**Comment by jboreiko** [comment]
Blah I forgot about sweep.  So basically sweep makes guaranteeing anything pretty much impossible and thus the answer to “what do I do when I hit this error and I run sweep?” is you restore from backup?
In a world where you’re not running sweep I think the guarantee discussed holds true and thus the steps to address still hold true.

I think we need to very clearly document all of this somewhere, likely the atlas documentation on github.

TomP

=============================
From: John

I agree with Coda that we can only state that T2 is correct if we can ensure that no data was purged from T2 based on the existence of T3 data.  The rest of the issues I can come up with are all corruption of the T3 issued timestamps and wouldn’t effect the earlier T2 data.  I wonder if we restricted sweep to remain 1M behind the current largest timestamp we could make this roll back to T2 possible on systems that would also like to have sweep running.
 
The other issue I would be concerned about is the fact that multiple timestamp servers indicates that there may well be multiple lock services running as well.  That said, again, I can only come up with routes to corruption for the T3 timestamp respecting transactions.  One consequence you would see on earlier transactions would be a large number of roll backs as neither reads nor writes running around T3 would block on the currently held locks in the original lock service.  Again this wouldn’t affect correctness.
 
I know this has been brought up in discussion before but it seems like the safest solution here would be to have a recorded set of leaders written in the db to be checked by any connecting leader service.
 
===============================
From: Zach
 
//Adding some folks who've seen this from PG-landia
PDS 43647
 
===============================
 
My shortened understanding:
·         We hand out time T1 and write data
·         We hand out time T3 > T1 and write data
·         We hand out time T2, where T1 < T2 < T3 and write data.  This retroactively invalidates the data at T3.
 
This is correct IF AND ONLY IF the only writes we made were transactional.  For example, if you ran sweep after writing T3, that could remove data at T1 and thus mess up T2.
 
(Side note – perhaps we should throw an exception in the lock server if someone tries to lock a time that is below the immutable timestamp?)
 
Thanks,
Coda
 
 ===================================
 
Hey guys,
 
<redacted>
 
The main issue with the MultipleRunningTimestampServiceError (MRTSE) is that it shows itself at an arbitrary point in time AFTER actual corruption could have occurred as a result.  Situation:
PersistentTimestampService (PTS) 1 is our lon- running good timestamp service
PTS1 allocates more timestamps
It’s current in memory upper limit is X, which it has hit and thus needs more
It successfully performs a _timestamp CAS (expects=X, sets=X+1M)
It updates it’s in memory upper limit to X+1M and now has the range (X, X+1M] to hand out to it’s clients
PTS2 (the evil one) spins up because someone spun up another service against the same keyspace without leadership election
It reads the current value of _timestamp which is X+1M
It successfully performs a _timestamp CAS (expects=X+1M, sets=X+2M)
It sets its in memory upper limit to X+1M and now has the range (X+1M, X+2M] to hand out to it’s clients
PTS1’s clients do some txns with timestamps X through X+100
PTS2’s clients do some txns with timestamps X+1M through X+1M+100
PTS1’s clients do some txns with timestamps X+101 through X+200 ——>  This is corruption****.  We have time traveled back in time.
PTS1 hands out the rest of it’s timestamps through X+1M
PTS1 goes to allocate more timestamps
It’s current in memory upper limit is X+1M
It fails when attempt to perform a _timestamp CAS (expects=X+1M, sets=X+2M), because the real value of _timestamp is X+2M, not X+1M
It throws MRTSE
**** corruption: What does this actually mean?  The transactions that occurred using timestamps from PTS2 happened chronologically before a set of transactions from clients of PTS1 with lower timestamps.  Therefore the txns from PTS2’s clients might have otherwise read data from PTS1’s clients txns if they had actually occurred in the correct chronological order and thus those transactions are corrupt.  The txns written by clients of PTS1 are in no way affected by those written by PTS2’s clients because PTS1’s timestamps are strictly less than PTS2’s timestamps.
 
Therefore in theory we should be able to guarantee that txns with timestamps <= what PTS1 was expecting (X+1M) when it threw the error are actually not corrupt and are instead perfectly fine.  If we treat that timestamp as the “backup timestamp” and fetch a new fresh timestamp (after guaranteeing everything is okay and only 1 PTS is running) to use as the “fast-forward timestamp”.  We should be able to treat this the same way we’d treat a restore.  Use the clean transactiosn range CLI to delete everything that occurred after X+1M and then fast-forward to the point in time we know to be strictly after any writes have taken place.
 
Does this make sense?  Are their holes?  Sorry for the word vomit.
 
TomP

**Comment by gsheasby** [comment]
This doesn't make sense without HA and a backup story.
