### ISSUE TITLE
_timestamp somehow created without corresponding table metadata for many many people

### ISSUE THREAD

**Issue by clockfort** [palantir/atlasdb#636]
It's probably something weird with how early / basic in the atlas startup _timestamp needs to be made.

**Comment by rhero** [comment]
Bumping this to the top of the todo because so far it's happened to **every** single customer on **every** single upgrade they've done (because upgrade scripts read all the tables). The error message also says to contact palantir support, and lots of people have been following the advice of the error message...


[main] ERROR c.p.a.k.c.CassandraKeyValueService - Found a table _timestamp that did not have persisted Atlas metadata. If you recently did a Palantir update, try waiting until schema upgrades are completed on all backend CLIs/services etc and restarting this service. If this error re-occurs on subsequent attempted startups, please contact Palantir support.

**Comment by gbrova** [comment]
@gsheasby You reopened this after merging #716 - is there a reason this isn't fixed?

**Comment by gsheasby** [comment]
@shashiadi - would you be able to check if this fixes the issue with your upgrade CLI for AtlasDB 0.12.0, please?

**Comment by hsaraogi** [comment]
This is fixed.
