### ISSUE TITLE
CassandraKVS#getRowsForSingleHost() appears to unnecessarily load full cell history

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#678]
`CassandraKVS#getRowsForSingleHost()` builds a `SliceRange` which includes all Cassandra row columns (resulting in the loading of the full history of the row).  It then discards all values when the exception of the max value less than the passed in `startTs`.  

This is particularly odd considering that if you instead only load a subset of the columns the `Cassandra#getRows()` method instead delegates to `Cassandra#getRowsForSpecificColumns()` which by passes the full loading of the history by instead using a call to `loadWithTs()` with `loadAllTs` set to false.

Again tagging in @clockfort / @tmgordeeva for some historical context

**Comment by tpetracca** [comment]
Because the filtering on the "all columns" code path doesn't explicitly filter versions so much as implicitly do it via the fact that we expect List<ColumnOrSuperColumn> as returned by Client.multiget_slice to be ordered when it gets passed through ValueExtractor, we should probably create a test (if it doesn't already exist) that validates that we read the most recent version less than our startTs in that codepath for cases when there are multiple versions less than the startTs.

Or we should move that code over to a codepath more like the getRowsForSpecificColumns() one

**Comment by tmgordeeva** [comment]
I sent you an internal wiki page detailing more about this. The BLUF is you can't just share the getRowsForSpecificColumns code path because the cassandra column name includes the atlas column name and the atlas timestamp. So if you don't know what columns you want, you'll get all the columns including older versions.

**Comment by tpetracca** [comment]
But don't we know the schema upfront and thus should be able to just say "no specific column" -> "specifically all the columns"

**Comment by tmgordeeva** [comment]
Yes, we should do that in the generated code when we have static columns (not sure why we didn't already - that page already talks about that and I guess we lost track of it). We can't do that for dynamic columns though.
