### ISSUE TITLE
Impossible RF should result in immediate failure of C* KVS

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#701]
The Cassandra KVS start up checks should hard fail if they find a situation in which the Cassandra config contains an impossible RF given the number of Cassandra nodes it is aware of.

**Comment by jboreiko** [comment]
@NeilRickards

**Comment by clockfort** [comment]
There was previously logic that poorly attempted to do this.

I removed it because doing it correctly for combinations of the following features seemed like more trouble than it was worth:
- people with multiple datacenters and different RFs per DC (calculating if EACH_QUORUM can be achieved here is not trivial)
- people whose config has small number of nodes and they autodiscover the rest of the nodes from this seed (hard to fail early, would have to fail after node discovery)
- there are some really wonky configurations that can happen when people are doing datacenter migrations

Feel free to add the feature in, just know it's non-trivial and has edge cases.

**Comment by NeilRickards** [comment]
Can we do a simple check that will guard against the common failure mode: total seed nodes = 1 and RF > 1?
Alternatively, blocking on keyspace creation unless quorum can be achieved would at least avoid the borked state. You kinda get this for free with the new lock table, except the error message won't be good, and the locks table will be in a borked state

**Comment by tpetracca** [comment]
@clockfort generally agree with your sentiments here and agree we'd have to fail after node discovery.  I think we could clean this stuff up and protect the datacenter migrations with a flag indicating that we're doing such a thing (sort of like safetyDisabled was but more targeted at datacenter or rf changes).  In terms of different RFs per DC, I understand on the cassandra side that this is possible but even getting to this configuration would require manual altering of the keyspace given that we only expose a single `replicationFactor` configuration in Atlas anyway.  

Given the number of times this crops up I think it's worth attempting to address.

**Comment by clockfort** [comment]
Yeah, I didn't really mean to scare someone away from doing this, just wanted to enumerate things they may not of thought of.

Don't get me wrong, I'm very on-board with changes that give people good enough error messages that they don't ask me to look at their stack traces whenever something explodes due to poor configuration.

Do a sane thing that works for 99% of people and leave an escape hatch for the 1%.

**Comment by gsheasby** [comment]
@hsaraogi - can you confirm if this is already fixed?

**Comment by rhero** [comment]
@gsheasby - why would we think this is fixed?

**Comment by gsheasby** [comment]
There were changes to the Cassandra KVS startup code that were in-flight at the time when I made that comment. I assume that Himangi was reviewing the changes at the time, and I pinged her (possibly as part of a backlog grooming session?) to see if the changes also fix this issue.

**Comment by rhero** [comment]
Related: #931.

**Comment by gsheasby** [comment]
We believe this has been done - @hsaraogi to confirm

**Comment by hsaraogi** [comment]
Yup, on startup we will fail if the config RF is set to a non-meaningful value with respect to the number of nodes/DCs.
