### ISSUE TITLE
Root cause recurring schema mutation lock dead lock

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#815]
Several users have seen schema mutation lock dead locks that have required manual intervention.  Schema mutating events should be relatively rare and I would like to determine why we are seeing these issues so frequently.  A good starting point would be to request the full logs (product + cassandra) from a deployment who has seen this issue repeatedly.  From there we should be able to track down the moment when the schema lock holding node died and why.  A related internal ticket PDS-44932

**Comment by tpetracca** [comment]
Will help inform the path forward for #805

**Comment by gsheasby** [comment]
We found one potential cause of spurious schema mutations, which was fixed in #771 (see [this comment](https://github.com/palantir/atlasdb/pull/771/files#diff-0137a65051be7916d0f8547ba73f6cdbR310)). This method got called on startup, and may have resulted in needless schema mutations if we had `com.foo.MyCompactionStrategy` in one place, and `MyCompactionStrategy` in the other.

If this happened, we would expect to see the following message in the logs, shortly before the "truncate _locks" message:
`log.warn("Upgrading table {} to new internal Cassandra schema", tableRef);` ([code](https://github.com/palantir/atlasdb/blob/develop/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java#L251))

**Comment by jboreiko** [comment]
As a next step I'm hoping we can identify this as the code path that was used by our clients before they lost the lock.

**Comment by jboreiko** [comment]
Closing as we have discovered several instances where the schema mutation lock was acquired unnecessarily.  We believe these lead to the instances of dead lock seen here.
