### ISSUE TITLE
Randomly redirecting a query can redirect back to the same host

### ISSUE THREAD

**Issue by hsaraogi** [palantir/atlasdb#885]
Transactions retry total of 6 times and 3 times per host.
If random redirection directs to the same host, transactions fail without actually retrying multiple nodes. (CassandraClientPool#runWithRetryOnHost).

**Comment by gbrova** [comment]
We noticed this as part of work for #819

**Comment by gbrova** [comment]
We briefly discussed this today, but wanted to also capture it here: I'm not convinced attempts 4, 5, and 6 are always on the same host. 

In [CassandraClientPool:478](https://github.com/palantir/atlasdb/blob/develop/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java#L478), we set `shouldRetryOnDifferentHost = true`, but we never set it to `false` again so all subsequent iterations will get a new random host on line 463.  

So I expect attempts 1-3 will all be on the same host, and attempts 4-6 will be on different hosts (subject to randomization).  This would give us a total of 4 chances to pick a live host; having said that, 4 independent attempts is still not great (if half the nodes are down, we'll fail with 1/16 ~= 6% probability), so it could still be worthwhile to try different hosts.

**Comment by jeremyk-91** [comment]
I had a brief look into this and as far as I can tell @gbrova's analysis is right (1-3 on same, 4-6 randomly picked). Ensuring that (if possible) 4 distinct nodes are attempted would improve the probability - using the half case you get (nC4)/(2nC4) which tends to 1/16 in the limit but does better for smaller n. For example if n=3 (6 node cluster) you always succeed, and if n=6 (12 nodes) the failure probability is 1/33 instead of 1/16.

Simple fix is to add a way of grabbing a host that calls getRandomHostByActiveConnections with a filter that also allows users to exclude specific hosts.

Will get to this on Monday.
