### ISSUE TITLE
Upgrade target compatibility for atlasdb-commons & commons-db to at least Java 1.7

### ISSUE THREAD

**Issue by schlosna** [palantir/atlasdb#961]
As a developer of AtlasDB, I want to write Java code targeting Java 7 and 8 features, especially on backend modules that require heavy use of exception handling (try-with-resources) and stream operations.

Several AtlasDB modules currently target Java 6 for source & bytecode compatibility. We should be able to bump source & target compatibility for several core backend modules such as `atlasdb-commons`, `commons-db` to at least `1.7` if not `1.8`.

Current Java 6 targeted modules:
```
$ a targetCompatibility | a 1.6
atlasdb-commons/build.gradle:7:targetCompatibility = 1.6
commons-annotations/build.gradle:4:targetCompatibility = 1.6
commons-api/build.gradle:4:targetCompatibility = 1.6
commons-db/build.gradle:4:targetCompatibility = 1.6
commons-executors/build.gradle:7:targetCompatibility = 1.6
commons-proxy/build.gradle:4:targetCompatibility = 1.6
lock-api/build.gradle:7:targetCompatibility = 1.6
```

**Comment by schlosna** [comment]
@clockfort @rjullman and @berler for SA on potential downstream impacts. I think bumping to Java 8 be safe for backend `atlasdb-commons` & `commons-db`

**Comment by gsheasby** [comment]
I agree - was actually thinking about this earlier this afternoon. Now that the code is not copied internally, can we bump compatibility?

Why would we stop at 1.7?

We should probably finish moving internal code internally (e.g. #891, #958) before bumping dependencies.

**Comment by schlosna** [comment]
I don't think we should stop at 1.7, but the motivation was when I wanted to use suppressed exceptions in #959 from a place that we should be able to now.

I'm fine waiting for those to merge and have green builds based on them. Created #962 in the meantime to bump those 2 modules to Java 8.

**Comment by j-baker** [comment]
We should make it 1.8 so that we can add a stream method to batchingvisitable type things.

Sent from my iPhone

On Sep 21, 2016, at 15:35, Glenn Sheasby <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree - was actually thinking about this earlier this afternoon. Now that the code is not copied internally, can we bump compatibility?

Why would we stop at 1.7?

We should probably finish moving internal code internally (e.g. #891<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_atlasdb_issues_891&d=DQMGaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=mzXajGbPp7kc5a_CRzXttisFRf8mEsV3gcMrXd3MRoc&m=U71oPzeomIYVl3mbSvC9yGMAIfx6v2YaMUR_9uWtcUw&s=su5KH_NyR5oycWzxMwn-e0bKDmEj_8VR3GiG6GiCrCw&e=>, #958<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_atlasdb_pull_958&d=DQMGaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=mzXajGbPp7kc5a_CRzXttisFRf8mEsV3gcMrXd3MRoc&m=U71oPzeomIYVl3mbSvC9yGMAIfx6v2YaMUR_9uWtcUw&s=LRenTPwVRm4t6yTu1DyFzcefU115mlBvQatDFzRmtjw&e=>) before bumping dependencies.
