### ISSUE TITLE
Sweep shouldn't OOM when iterating through RowResults

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#982]
From internal QA ticket 96341.

@berler said:
In other words, this OOM has nothing to do with paging on the KVS layer. It is a problem in the Sweep layer which takes an iterator of RowResults and turns that into an ImmutableList of RowResults, and then for each row loads all the Cells for that row. The problem code is this:

https://github.com/palantir/atlasdb/blob/0.15.1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTaskRunnerImpl.java#L144-L148

Batching at the Cell level needs to be implemented in Sweep (since even if the KVS batched loading the Cells, it stuffs all the Cells into a map before actually doing the sweep), currently it only batches at the RowResult level.

**Comment by gbrova** [comment]
Instead of batching at the cell level, a much easier way to address this is to dynamically decrease the batch size. The internal ticket occurred when running with batch size = 5000, so there is lots of room to decrease it. 

For example, instead of adding all the Cells corresponding to the 5000 RowResults, we could add Cells for one RowResult at a time while the number of cells added is smaller than maxCellsThatWillFitInMemory. 

This will work as long as any single RowResult has fewer cells than maxCellsThatWillFitInMemory (which feels very likely to me, but we should confirm); the major advantage of doing it this way is we wouldn't need an API break in KVS (which we likely would need if we wanted to support cell paging for a single row).

**Comment by berler** [comment]
If possible it would be nice to have the BackgroundSweeper batch on the Cell level instead of assuming that a Row will always fit in memory.  This doesn't require an API break.  You could implement it as a new method in SweepTaskRunner (so you can either batch on rows or cells), or if you don't want to maintain two versions, the existing method could batch internally and just return aggregate results from multiple batches.

**Comment by rhero** [comment]
I'm slightly confused here, I thought the newer implementation of sweep lets you page through a single cell? Talking about [column paging for sweep](https://palantir.github.io/atlasdb/html/configuration/cassandra_KVS_configuration.html?highlight=experimental#column-paging-for-sweep-experimental).

**Comment by tkleingarn** [comment]
Tagging @rhero for SA, this ticket spun up from QA-96341 and I wanted to be sure we have this prioritized in the near future.

Within SweepTaskRunner, for a given RowResult load we should load cells in batches instead of loading all cells.  Note that this is separate from the improvements made to sweeping a cell with a large number of historical versions.

@gbrova I would prefer an improvement to this that assumes we will encounter a row who's cells will not fit into memory.  Implementing a static maximum on the number of cells loaded for a given row seems risky.  From prior comments I think @berler and @gsheasby agree with that as well.

**Comment by tkleingarn** [comment]
Hey @gbrova Robert mentioned that you were starting work on this.  Let us know if you'd like any advice, tagging @berler for SA.  This is high priority on our end, as it could result in an OOM for anyone with a wide row.

**Comment by gbrova** [comment]
Just talked to Robert, makes sense. I just pushed my changes on #1068 and tagged @berler.

**Comment by tkleingarn** [comment]
Reopening as this does not appear to be resolved.  We encountered another OOM when loading RowResults in SweepTaskRunnerImpl

You can see we have a problem when loading an arbitrarily large RowResult:
try (ClosableIterator<RowResult<Value>> valueResults = sweeper.getValues(tableRef, range, sweepTs);

Batching is done on rows instead of cells, meaning that when we load batches of rows that have dynamic columns we can load too much. One table in our schema had tons of rows that had 9000-10,000 columns, so trying to batch load multiple of these is probably what caused the oom. Tagging @gbonik for additional thoughts.

**Comment by rhero** [comment]
Ack'd. We're prioritizing this right behind the backup lock work so it's a stretch goal for this week, but will likely be looked at next week. In the meantime if you guys are able to provide a more isolated repro with logging, that would be great (feel free to attach to the internal QA ticket and ping us).

**Comment by tkleingarn** [comment]
hprof from end-to-end testing is attached to our internal QA ticket (QA-97282).

@gsheasby - here is @gbonik 's test that repros the sweep oom, which you can add to AbstractSweeperTest and run locally (takes a while to run and OOM).

`
    @Test
    public void testOom() {
        createTable(SweepStrategy.CONSERVATIVE);
 
        for (int col = 0; col < 10000; ++col) {
            Map<Cell, byte[]> toPut = new HashMap<>();
            for (int row = 0; row < 1000; ++row) {
                Cell cell = Cell.create(
                        Integer.toString(row).getBytes(),
                        Integer.toString(col).getBytes());
                toPut.put(cell, "foo".getBytes());
            }
            kvs.put(TABLE_NAME, toPut, col + 1000);
            txService.putUnlessExists(col + 1000, col + 1000);
            System.out.println("inserted col " + col);
        }
        System.out.println("starting sweep");
        completeSweep(30000);
    }
`

**Comment by gsheasby** [comment]
Handing off to @gmaretic as I'm out all next week.

The work so far is on a branch `fix/982-dbkvs-sweep-oom`. The idea is to reuse logic from Jeffrey's "getRowsColumnRange", but this time get timestamps and not Values.

**Comment by gsheasby** [comment]
Fixed by #1678.
